#### Example Configuration File ########################################################################################
[input]
source="file://./test.log"  ### Can be:  udp://xxxx:port; tcp://xxxx:port; http://xxxx:port
file_follow=true  ### For file only
file_offset="begin" ### Can be: 'end' or 'begin'
http_method="PUT" ### Cane be: 'POST' or 'PUT', empty will take both.

[filter]


[process]


[output]
destination="file://./text.result.txt" ### Can be: udp://xxxx:port; tcp://xxxx:port; http://xxxx:port/URI
format="json" ## Or 'bson', 'yaml',
http_method="POST" ## Or 'PUT'.
http_auth="Basic" ## Or 'Digest', empty means no auth required.
http_auth_username="" ##
http_auth_password="" ##
http_headers="" ## KEY:VALUE pares sepreated with \t or space.
bulk=true # Or false
bulk_mode="time" # Or 'count', means bulk time or by count
bulk_time="10s" # A time duration. Only effect when bulk_mode="time"
bulk_count=1000 # A integer for bulk by count. Only effect when bulk_mode="count"

